### ISSUE TITLE
#1 Create user profile form

### ISSUE THREAD

**Issue by JosteinRuen** [boolean-uk/team-dev-client-ex-2410-team1#13]
Create Profile

After successfully registering an account, the user will be taken to a Create Profile step-by-step form. All of the fields should be optional on the server, but the user’s first name and last name should be required on the client. After successfully completing the profile creation, the user is taken to the dashboard.

[Design](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=204-8131&t=zEFtsoD0sKc7tig8-0)

File structure, 4 steps:
src/pages/welcome/stepOne/index.js
src/pages/welcome/stepTwo/index.js
src/pages/welcome/stepThree/index.js

TODOS:
Step one (Basic info):
* Add username input field
* Remove back button

Step two (Contact info):
* Input fields: Email, Mobile
--> If any of the fields are invalid, guide the user using a conditional pop up text
* Email should be autofilled based on what was registered

Step three, Submit button:
* Input fields: Bio
* Fix it so it does not look inactive when it should be active

**Comment by dogezen** [comment]
Are you going to use validations for email, mobile fields?

Also note that the UI screen allows users to see their passwords, which is not acceptable, we should change it where the user can instead have 2 password fields: `old password` and `new password` and optionally `new password confirmation`, so that on update, if old pwd is provided with a new pwd, then we can update the password server side. NOTE server will NEVER return the user's password.

I see no details about whether students can change their cohort and the start/end dates -> these should be editable only by teachers.

Also, since you're talking about a form, what should the behaviour be before / during and after submission (for errors, for example)?
