### ISSUE TITLE
#5 Create view user page

### ISSUE THREAD

**Issue by johnfa1508** [boolean-uk/team-dev-client-ex-2410-team1#16]
As part of the cohort manager, each user should have their personal profile page that displays their details. As a user, I would like to view other users' profile pages regardless of which cohort they are in or whether they are teachers or not.
A user with id=12 should have their profile page at the path /profile/12

[Design](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=195-8008&t=9MMyKWxWpM9ZRNUk-0)

File structure:
src/pages/profile/

TODOS:
* Implementation of design based on figma design
* Implementation of fields based on figma design
* If the id does not exist, 404 page

API fetch from: /users/{id}
Expected from API if the profile is a STUDENT:
{
  "status": "success",
  "data": {
    "user": {
      "id": 1,
      "firstName": "Alex",
      "lastName": "Walker",
      "userName": "Alex Walker",
      "githubUsername": "alex-walker",
      "email": "alex.walker@boolean.co.uk",
      "mobile": "07890 123456",
      "role": "STUDENT",
      "specialism": "Software Developer",
      "imageUrl": "URL",
      "cohort_id": 4,
      "start_date": "mm-yyyy",
      "end_date": "mm-yyyy",
      "biography": "Hello there!",
    }
  }
}

Expected from API if the profile is a TEACHER:
{
  "status": "success",
  "data": {
    "user": {
      "id": 2,
      "firstName": "Dylan",
      "lastName": "Green",
      "userName": "Dylan Green",
      "githubUsername": "dylan-green",
      "email": "teacher@test.com",
      "mobile": "07654 321098",
      "role": "TEACHER",
      "specialism": "Software Developer",
      "imageUrl": "URL",
      "job_title": "Software Development Instructor",
      "biography": "Hello there!",
    }
  }
}

**Comment by dogezen** [comment]
OK - would be good to mention that the Route `/profile/:ID` is to be a ProtectedRoute (ie, I need to be logged in) - since the description above is not clarifying this.

Also:
a) what should happen if :id is not a valid user id?
b) where are the details to be displayed onto the profile page coming from? Are you going to call a fetch when component loads, if yes, what's the endpoint to be called and what's the expected payload you are going to assume that comes back?
